In [1]:
#KNN Classifier
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_excel('C:\\Users\\ADITYA\\Desktop\\New folder\\Normalized Data Inventory - Well Logs exp.xlsx')
pd.set_option("max_rows", None)
print (df)

     Depth(ft.)  Caliper (in.)  GR (API)  RHOB (g/cc.)  Density Porosity  \
0          1200          4.130   209.760         2.604          0.003631   
1          1202          4.139   182.370         2.611         -0.000605   
2          1204          4.145   209.990         2.578          0.019367   
3          1206          4.131   163.030         2.626         -0.009684   
4          1208          4.144   221.040         2.634         -0.014526   
5          1210          4.134   188.280         2.575          0.021183   
6          1212          4.136   170.530         2.569          0.024814   
7          1214          4.141   130.120         2.588          0.013315   
8          1216          4.145   128.870         2.500          0.066575   
9          1218          4.139   146.940         2.568          0.025420   
10         1220          4.148   170.890         2.572          0.022999   
11         1222          4.139   146.180         2.593          0.010289   
12         1

In [3]:
df1=df.drop(columns =['Classification'])
X = df1
y = df['Classification']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [13]:
y_pred = classifier.predict(X_test)

In [14]:
y_pred

array([1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 1, 1, 2,
       1, 2, 2, 2, 2, 1, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 1, 0, 2, 2, 2,
       1, 0, 0, 2, 2, 2, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 1, 2, 2, 1, 2, 1,
       0, 1, 2, 2, 2, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 1, 1, 2, 2, 1, 1, 1,
       0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0], dtype=int64)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[31  0  3]
 [ 0 21  2]
 [ 0  4 40]]
              precision    recall  f1-score   support

           0       1.00      0.91      0.95        34
           1       0.84      0.91      0.87        23
           2       0.89      0.91      0.90        44

    accuracy                           0.91       101
   macro avg       0.91      0.91      0.91       101
weighted avg       0.92      0.91      0.91       101



In [20]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)

In [21]:
acc

0.9405940594059405